---
title: AresMUSH
timezone: UTC
collections:
  posts:
    title: Blog Posts
    output: true
    permalink: /blog/:title.html
  uploads:
    title: Uploads
    output: true
email: faraday@aresmush.com
tagline: A New Breed of MUSH Server
description: AresMUSH is a new kind of server for online text-based roleplaying games
  (MUSHes).
baseurl: ''
url: ''
twitter_username: lynnnoton
github_username: lynnfaraday
markdown: kramdown
theme: minima
paginate: 12
paginate_path: "/blog/:num/"
plugins:
- jekyll-feed
- jekyll-paginate
highlighter: rouge
algolia:
  application_id: NI38C577BA
  index_name: aresmush.com
  search_api_key: 29793fd9084a3446072c14e471e32589
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: ruby
